language: java
jdk:
- oraclejdk8
#Probar si con esto se ejecuta kafka antes que la aplicacion
env:
  global:
  - ZOOKEEPER_PEERS=localhost:2181
  - KAFKA_PEERS=localhost:9092
  - DEMO_KAFKA=demo

before_install:
- wget http://www.us.apache.org/dist/kafka/0.10.2.0/kafka_2.12-0.10.2.0.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"


after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  sauce_connect:
    username: "dashboard2b"
    access_key: "176d6582-28d1-41ab-8982-97fbce376c55"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
